[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
numReplicas = 1
startCommand = "python -m gunicorn app:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ["python39", "gcc"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = ["python -m pip install gunicorn"] 